MACRO(SIGN_TARGET target)
  IF(WITH_SIGNCODE)
    IF(WIN32)
      SET(target_file $<TARGET_FILE:${target}>)
      MESSAGE(STATUS "TARGET_FILE: <${target_file}>")
      ADD_CUSTOM_COMMAND(TARGET ${target} 
                         COMMAND signtool ARGS sign ${SIGN_OPTIONS} ${target_file})
    ENDIF()
  ENDIF()
ENDMACRO()
